<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir).'/mediawiki';

return array(
    'WrappedString\\' => array($vendorDir . '/wikimedia/wrappedstring/src'),
    'Wikimedia\\Composer\\' => array($vendorDir . '/wikimedia/composer-merge-plugin/src'),
    'Wikimedia\\Assert\\Test\\' => array($vendorDir . '/wikimedia/assert/tests/phpunit'),
    'Wikimedia\\Assert\\' => array($vendorDir . '/wikimedia/assert/src'),
    'WikiPathways\\OntologyTags\\Tests\\' => array($baseDir . '/extensions/OntologyTags/tests/phpunit'),
    'WikiPathways\\OntologyTags\\Maintenance\\' => array($baseDir . '/extensions/OntologyTags/maintenance'),
    'WikiPathways\\OntologyTags\\' => array($baseDir . '/extensions/OntologyTags/src'),
    'WikiPathways\\GPML\\Tests\\' => array($baseDir . '/extensions/GPML/tests/phpunit', $baseDir . '/extensions/GPML/tests/phpunit'),
    'WikiPathways\\GPML\\Maintenance\\' => array($baseDir . '/extensions/GPML/maintenance', $baseDir . '/extensions/GPML/maintenance'),
    'WikiPathways\\GPML\\Converter\\Tests\\' => array($baseDir . '/extensions/GPMLConverter/tests/phpunit', $baseDir . '/extensions/GPMLConverter/tests/phpunit'),
    'WikiPathways\\GPML\\Converter\\Maintenance\\' => array($baseDir . '/extensions/GPMLConverter/maintenance', $baseDir . '/extensions/GPMLConverter/maintenance'),
    'WikiPathways\\GPML\\' => array($baseDir . '/extensions/GPML/src', $baseDir . '/extensions/GPMLConverter/src', $baseDir . '/extensions/GPML/src', $baseDir . '/extensions/GPMLConverter/src'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'RemexHtml\\' => array($vendorDir . '/wikimedia/remex-html/RemexHtml'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'MediaWiki\\Extension\\UserLoginLog\\' => array($baseDir . '/extensions/UserLoginLog/src'),
    'Eloquent\\Composer\\NpmBridge\\' => array($vendorDir . '/eloquent/composer-npm-bridge/src'),
    'Composer\\Semver\\' => array($vendorDir . '/composer/semver/src'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'CLDRPluralRuleParser\\' => array($vendorDir . '/wikimedia/cldr-plural-rule-parser/src'),
);
