<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir).'/mediawiki';

return array(
    'Liuggio' => array($vendorDir . '/liuggio/statsd-php-client/src'),
    'Less' => array($vendorDir . '/oyejorge/less.php/lib'),
    'ComposerHookHandler' => array($baseDir . '/includes/composer'),
    '' => array($vendorDir . '/cssjanus/cssjanus/src'),
);
