<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir).'/mediawiki';

return array(
    'phpDocumentor\\Reflection\\' => array($vendorDir . '/phpdocumentor/reflection-common/src', $vendorDir . '/phpdocumentor/reflection-docblock/src', $vendorDir . '/phpdocumentor/type-resolver/src'),
    'XdgBaseDir\\' => array($vendorDir . '/dnoegel/php-xdg-base-dir/src'),
    'WrappedString\\' => array($vendorDir . '/wikimedia/wrappedstring/src'),
    'Wikimedia\\Composer\\' => array($vendorDir . '/wikimedia/composer-merge-plugin/src'),
    'Wikimedia\\Assert\\Test\\' => array($vendorDir . '/wikimedia/assert/tests/phpunit'),
    'Wikimedia\\Assert\\' => array($vendorDir . '/wikimedia/assert/src'),
    'WikiPathways\\GPML\\Tests\\' => array($baseDir . '/extensions/GPML/tests/phpunit', $baseDir . '/extensions/GPML/tests/phpunit'),
    'WikiPathways\\GPML\\Maintenance\\' => array($baseDir . '/extensions/GPML/maintenance', $baseDir . '/extensions/GPML/maintenance'),
    'WikiPathways\\GPML\\Converter\\Tests\\' => array($baseDir . '/extensions/GPMLConverter/tests/phpunit', $baseDir . '/extensions/GPMLConverter/tests/phpunit'),
    'WikiPathways\\GPML\\Converter\\Maintenance\\' => array($baseDir . '/extensions/GPMLConverter/maintenance', $baseDir . '/extensions/GPMLConverter/maintenance'),
    'WikiPathways\\GPML\\' => array($baseDir . '/extensions/GPML/src', $baseDir . '/extensions/GPMLConverter/src', $baseDir . '/extensions/GPML/src', $baseDir . '/extensions/GPMLConverter/src'),
    'Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'WMDE\\HamcrestHtml\\' => array($vendorDir . '/wmde/hamcrest-html-matchers/src'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\VarDumper\\' => array($vendorDir . '/symfony/var-dumper'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Symfony\\Component\\Debug\\' => array($vendorDir . '/symfony/debug'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Seld\\JsonLint\\' => array($vendorDir . '/seld/jsonlint/src/Seld/JsonLint'),
    'RemexHtml\\' => array($vendorDir . '/wikimedia/remex-html/RemexHtml'),
    'Psy\\' => array($vendorDir . '/psy/psysh/src/Psy'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'MediaWiki\\Extension\\UserLoginLog\\' => array($baseDir . '/extensions/UserLoginLog/src'),
    'JsonSchema\\' => array($vendorDir . '/justinrainbow/json-schema/src/JsonSchema'),
    'JakubOnderka\\PhpConsoleColor\\' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
    'Eloquent\\Composer\\NpmBridge\\' => array($vendorDir . '/eloquent/composer-npm-bridge/src'),
    'Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
    'Composer\\Spdx\\' => array($vendorDir . '/composer/spdx-licenses/src'),
    'Composer\\Semver\\' => array($vendorDir . '/composer/semver/src'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'CLDRPluralRuleParser\\' => array($vendorDir . '/wikimedia/cldr-plural-rule-parser/src'),
);
